title: Fleur Oils
description: >
  Fleur Oils celebrate the age-old traditions of wellness with essential oils. Whether you desire common oils or exotic, all of our selections are sourced from respected Fair Trade farms and cooperatives around the world.
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: compressed

filter:
  - rank: 1
    name: "Essential Oils"
    filter: "essential-oil"

  - rank: 2
    name: "Synergies"
    filter: "synergy"

  - rank: 3
    name: "Floral Waters"
    filter: "floral-water"

  - rank: 4
    name: "Massage Oils"
    filter: "massage-oil"

  - rank: 5
    name: "Candles & Soaps"
    filter: "soap"

  - rank: 6
    name: "Diffusers"
    filter: "diffuser"



product-category:
  - rank: 1
    name: "Essential Oils"
    link: "esential-oil"

  - rank: 2
    name: "Synergies"
    link: "synergies"

  - rank: 3
    name: "Floral Waters"
    link: "floral-water"

  - rank: 4
    name: "Massage Oils"
    link: "massage-oil"

  - rank: 5
    name: "Candles & Soaps"
    link: "candle-soap"

  - rank: 6
    name: "Diffusers"
    link: "diffuser"


social-media:
  - link: "https://www.facebook.com/SpaOrder/"
    image: "facebook.png"

  - link: "https://twitter.com/spa_order"
    image: "twitter.png"

  - link: "https://www.instagram.com/spaorder/"
    image: "instagram.png"


collections:
  product:
    output: true
    permalink: /product/:path/

  products:
    output: true
    permalink: /products/:path/