title: Fleur Oils
description: >
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: compressed

filter:
  - id: 1
    name: "Essential Oils"
    filter: "essential-oil"

  - id: 2
    name: "Synergies"
    filter: "synergy"

  - id: 3
    name: "Floral Waters"
    filter: "floral-water"

  - id: 4
    name: "Massage Oils"
    filter: "massage-oil"

  - id: 5
    name: "Candles & Soaps"
    filter: "soap"

  - id: 6
    name: "Diffusers"
    filter: "diffuser"



product-category:
  - id: 1
    name: "Essential Oils"
    link: "esential-oil"

  - id: 2
    name: "Synergies"
    link: "synergies"

  - id: 3
    name: "Floral Waters"
    link: "floral-water"

  - id: 4
    name: "Massage Oils"
    link: "massage-oil"

  - id: 5
    name: "Candles & Soaps"
    link: "candle-soap"

  - id: 6
    name: "Diffusers"
    link: "diffuser"


social-media:
  - link: "https://www.facebook.com/SpaOrder/"
    image: "facebook.png"

  - link: "https://twitter.com/spa_order"
    image: "twitter.png"

  - link: "https://www.instagram.com/spaorder/"
    image: "instagram.png"


collections:
  product:
    output: true