title: Fleur Oils
description: >
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


social-media:
  - link: "https://www.facebook.com/SpaOrder/"
    image: "facebook.png"

  - link: "https://twitter.com/spa_order"
    image: "twitter.png"

  - link: "https://www.instagram.com/spaorder/"
    image: "instagram.png"